### ISSUE TITLE
Stupid Guy #1 

### ISSUE THREAD

**Issue by karduski24** [KSCHdsc/BlackCap-Grabber#73]
Dont buy from this guy , when he send the file .rar he grub yours ip and if stress him he make ddos on yours router. Dont believe in this stupid young boy

**Comment by KSCHdsc** [comment]
you've certainly got the wrong person because I haven't been selling blackcap premium for 2 months now, we're too busy making a website to be able to make a premium sales API. but when I was selling the premium the source code of this one was totally open source and did not collect the "ip" of my customers you are simply stupid

**Comment by karduski24** [comment]
nice to hear the answer of a charlatan , do you have psychological problems or do not know , keep collecting the information of others that in a few days you will have to collect your verdict... lol

**Comment by KSCHdsc** [comment]
Don’t be stupid… 164 stars and you say i’m à charlatan get blocked
